name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Introduzione
      - name: Build and push Intro Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "1 - Introduzione/Ch1"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/intro-ch1:latest

      - name: Build and push Intro Challenge 2
        uses: docker/build-push-action@v5
        with:
          context: "1 - Introduzione/Ch2"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/intro-ch2:latest

      # Cookies
      - name: Build and push Cookie Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "2 - Cookies/Ch1 - Cookie login"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cookie-ch1:latest

      - name: Build and push Cookie Challenge 2
        uses: docker/build-push-action@v5
        with:
          context: "2 - Cookies/Ch2 - Session bruteforce"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cookie-ch2:latest

      - name: Build and push Cookie Challenge 3
        uses: docker/build-push-action@v5
        with:
          context: "2 - Cookies/Ch3 - Cookie shop"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cookie-ch3:latest

      - name: Build and push Cookie Challenge 4
        uses: docker/build-push-action@v5
        with:
          context: "2 - Cookies/Ch4 - HMAC Cookie"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cookie-ch4:latest

      # CSRF
      - name: Build and push CSRF Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "3.0 - CSRF/Ch1 - Money transfer"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/csrf-ch1:latest

      # SSRF
      - name: Build and push SSRF Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "3.1 - SSRF/Ch1 - Private Webserver"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ssrf-ch1:latest

      # XSS
      - name: Build and push XSS Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "4 - XSS/Ch1 - Reflected XSS"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/xss-ch1:latest

      - name: Build and push XSS Challenge 2
        uses: docker/build-push-action@v5
        with:
          context: "4 - XSS/Ch2 - Stored XSS"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/xss-ch2:latest

      - name: Build and push XSS Challenge 3
        uses: docker/build-push-action@v5
        with:
          context: "4 - XSS/Ch3 - Stored XSS Forum Wrong Sanitization"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/xss-ch3:latest

      # SQLI
      - name: Build and push SQLI Challenge 1
        uses: docker/build-push-action@v5
        with:
          context: "5 - SQLI/Ch1 - WhiteBox Injection"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/sqli-ch1:latest

      - name: Build and push SQLI Challenge 2
        uses: docker/build-push-action@v5
        with:
          context: "5 - SQLI/Ch2 - Union Injection Filtered"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/sqli-ch2:latest

      - name: Build and push SQLI Challenge 3
        uses: docker/build-push-action@v5
        with:
          context: "5 - SQLI/Ch3 - Time Based Blind Injection"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/sqli-ch3:latest 
